# Generated by Django 5.0.4 on 2024-04-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default=None, upload_to='tours/%Y/%m'),
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together={('tour_name', 'category')},
        ),
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='tours/%Y/%m')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
            options={
                'unique_together': {('tour_name', 'tour')},
            },
        ),
    ]
