# Generated by Django 5.0.4 on 2024-05-06 11:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tag_tourdetail_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tourdetails', to='tours.tag'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourdetails', to='tours.tour'),
        ),
    ]
