# Generated by Django 5.0.4 on 2024-05-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tour_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourdetail'),
        ),
    ]
