# Generated by Django 5.0.4 on 2024-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_like_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'tour_name')},
        ),
    ]
